### ISSUE TITLE
Add option to reset 'filesToInclude'

### ISSUE THREAD

**Issue by itacud95** [shibayu36/vscode-search-in-current-file#13]
Once this extension has search the current file it would be nice to have a option for clearing out 'filesToInclude' field so one can search the whole workspace again. 

I see a similar issue has already been made here: https://github.com/shibayu36/vscode-search-in-current-file/issues/3. 

Let me know if I can help out with this, or if you can take a look at implementing this.

**Comment by shibayu36** [comment]
@itacud95 Sorry for my late response.

Is your usecase the same as https://github.com/shibayu36/vscode-search-in-current-file/issues/3#issuecomment-1425556121 ?  Can this comment solve your request?

**Comment by itacud95** [comment]
That looks like something that would work, but I have not tested it. I ended up switching to `editor.action.nextSelectionMatchFindAction` and `editor.action.previousSelectionMatchFindAction` for searching in-files.
