### ISSUE TITLE
[feature request] show line numbers in search results

### ISSUE THREAD

**Issue by gthbusr0** [shibayu36/vscode-search-in-current-file#16]
thank you for this extension that I heavily use.

Wondering if line numbers can also be included in search results so that when browsing them we have the ability to skip over to desired collocated code blocks bypassing few of them. for eg. if we eyeball first instance at line 10 and would like to ignore surrounding code block as it isn't applicable, we'd like to move on to the next nearby code block starting line 20 etc. (guestimated by line number).

**Comment by gthbusr0** [comment]
@shibayu36 hoping you can take a look and advise. thanks.

**Comment by shibayu36** [comment]
The search results display is simply using the standard SEARCH panel in VSCode. Because of this, I believe it's better not to add a line number feature to this extension.
Why don't you try searching the VSCode standard SEARCH panel settings to see if there's an option to add line numbers?

**Comment by gthbusr0** [comment]
@shibayu36 thank you! found the Search: Show Line Numbers option you reference.
